### ISSUE TITLE
how to access and use the generated passwords?

### ISSUE THREAD

**Issue by efx** [LedgerHQ/ledger-app-password-manager#7]
This looks like useful application to have on the secure devices. I was wondering how I would actually use the passwords I have generated.
Is there a way to copy selected passwords from the device to the host?
Or are there plans for a Chrome App UI for selecting them?
I can gladly contribute some documentation for the README to explain the process.

**Comment by parkerhoyes** [comment]
Yes, if you select a password label in the app and then press the left and right buttons at the same time, the Nano S will simulate an HID keyboard and type the password into the computer that your device is plugged in to.
